### ISSUE TITLE
Missing "SEND OK" response after AT+CIPSEND

### ISSUE THREAD

**Issue by kurta999** [espressif/esp-at#154]
I receive a HTTP GET response from ESP with +IPD. It's ~450 characters. After I response wth AT+CIPSEND, the response "SEND OK" often missing. I don't have any idea how this could happen, but it's a bit problematic beacuse in parser I'm expecting this message too.

Buadrate: 115200
AT version: V1.1.2.0
Board: ESP-WROOM-32

Any ideas?

**Comment by xcguang** [comment]
Could you provide some log and the commands you send?

**Comment by kurta999** [comment]
For WiFi setup:
https://pastebin.com/ZDqkLi0d
Hope this help, from function names you can relate which AT command is behind them.

And I use periodically AT+CIPSEND to send data to a remote server (measurements from sensor), but beside it I have setup HTTP server for configuring my device. Anyway for me strange things started to happens when I started to use Station+SoftAP mode. Example, yesterday I debugged my firmware, which means lot of restarts (toggling EN pin), sending the init sequence which I linked on pastebin, and after some time, ESP was unable to connect to ANY remote TCP server in Station+SoftAP mode. When I switched to Station mode, connection was successfull. I hade to completly erase the chip, afterwards it worked again with Station+SoftAP mode.

**Comment by mbedNoobNinja** [comment]
The same issue here!
### With a little difference:
- using HSPI interface.
-speed: 8 MHz
- using ESP32-WROOM-32 module.
-AT version: V1.1.3.0

Anyway, I am starting to suspect the problem is in **`libat_core.a`**.

Here is the [log](https://github.com/espressif/esp32-at/files/3073263/Bug.txt), what ESP is sent.
And here is what [PC](https://github.com/espressif/esp32-at/files/3073273/Bug.zip) is recv-ed

In short: There are two sockets opened!
- 1 TCP server is created by the ESP and 1 PC client connects to it.
- 1 UDP client connection is made by ESP to the PC. (UDP server is created by the PC and binded to its IP)

After first 200 ~ 250 UDP packets (sent by the ESP to the PC), ESP stops answering with **`SEND OK`** to the **`AT+CIPSEND=1,1400`** command & last UDP packet is not sent!

The strange thing here is SEND OK do arrive, after PC TCP client disconnects from the ESP TCP server,
and the last missing UDP packet finally is received on the PC. (This isn't in the pcap log. I noticed it later!)

Anyway. I also found other
### Problems:
- ### Sometimes the handshake signal is raised without any obvious reason:
Example:
```
AT+CIPSEND=1,1400
OK
>
handshake [assuming FLAG (read)]
<nothing comes later [DATALEN & DATA missing!]>
```
after reading `>` there is extra **single** handshake (which makes no sence).
**They should be tripple to make any sence**!
for example: **_read me I have data_** should look like this:

handshake [FLAG (read)]
handshake [DATALEN]
handshake [DATA]

- ### Sometimes on writing, handshake stages can not be validated:
Example:
```
write [FLAG (**MOSI**{0x02, 0x00, 0x00, 0x00} & **MISO** should be {'C', 0x00, 0x00, 0x00})]
handshake [DATALEN (**MOSI**{Lo, Hi, 0x00, 'A'} & **MISO** should be {'b', 0x00, 0x00, 0x00})]
handshake [DATA]
```
well 'C' response for the [FLAG] and 'b' for the [DATALEN] are frequently different.

I agree for [FLAG] it is normal to be different from time to time (yet write is kind of asynchronous) and you should make sure that the slave is on the same page as the master. But once [FLAG] is passed successfully, [DATALEN] should also always be successful too. (but somethimes it doesn't and that's the problem).

**Comment by kzoltaan** [comment]
same problem here. Is any solution for this?

**Comment by xcguang** [comment]
Can you try the latest master branch?
