### ISSUE TITLE
ESP8285, FlowControl not working, TX (GPIO1), RX (GPIO3), CTS (GPIO13), RTS (GPIO15)

### ISSUE THREAD

**Issue by Maintraxx** [espressif/esp-at#543]
## Environment

- Development Kit:      custom
- Module or chip used:  ESP8285
- IDF version: v2.1.0.0_esp32s2-409-gc9c1fc4
- Build System:         Make

## Problem Description
Hardware Flowcontrol is not working.
I have the following pin configuration: 

- TX (GPIO1)
- RX (GPIO3)
- CTS (GPIO13)
- RTS (GPIO15)

I'm activating the hardware flow control during runtime, but RTS and CTS don't do what they should. 

I adjust factory_param_data.csv:
```
PLATFORM_ESP8266,ESP8266_1MB,No OTA,0xfcfc,3,0,78,0,1,13,CN,115200,1,3,13,15,-1,-1
```

I did not find, where at_uart_task.c takes care of the RTS and CTS configuration. They are never really used and only stored in s_at_uart_port_pin which I guess is only for "at_pre_deepsleep_callback".

I think this is the responsible code: (i removed the ESP32) part:
```
            //Install UART driver, and get the queue.
            uart_driver_install(esp_at_uart_port, 1024, 2048, 10,&amp;esp_at_uart_queue, 0);
            if ((tx_pin == 15) && (rx_pin == 13)) {         // swap pin
                uart_enable_swap();
                assert((cts_pin == -1) || (cts_pin == 3));
                assert((rts_pin == -1) || (rts_pin == 1));
            } else {
                assert((tx_pin == 1) &amp;&amp; (rx_pin == 3));
            }
      
            uart_intr_config(esp_at_uart_port, &amp;intr_config);

            // set actual uart pins
            s_at_uart_port_pin.tx = tx_pin;
            s_at_uart_port_pin.rx = rx_pin;
            s_at_uart_port_pin.cts = cts_pin;
            s_at_uart_port_pin.rts = rts_pin;
```

In the NONOS Version, i found:

```
UART_SetFlowCtrl(uint8_t uart_no, UART_HwFlowCtrl flow_ctrl, uint8_t rx_thresh)
{
    if (flow_ctrl & USART_HardwareFlowControl_RTS) {
        PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTDO_U, FUNC_U0RTS);
        SET_PERI_REG_BITS(UART_CONF1(uart_no), UART_RX_FLOW_THRHD, rx_thresh, UART_RX_FLOW_THRHD_S);
        SET_PERI_REG_MASK(UART_CONF1(uart_no), UART_RX_FLOW_EN);
    } else {
        CLEAR_PERI_REG_MASK(UART_CONF1(uart_no), UART_RX_FLOW_EN);
    }

    if (flow_ctrl & USART_HardwareFlowControl_CTS) {
        PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTCK_U, FUNC_UART0_CTS);
        SET_PERI_REG_MASK(UART_CONF0(uart_no), UART_TX_FLOW_EN);
    } else {
        CLEAR_PERI_REG_MASK(UART_CONF0(uart_no), UART_TX_FLOW_EN);
    }
}
```

So, my question is:
Where is 
```
PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTDO_U, FUNC_U0RTS);
PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTCK_U, FUNC_UART0_CTS);
``` 
in the ESP-AT Version?

**Comment by ustccw** [comment]
@Maintraxx it is a good issue in deed. let me clarify it.

the uart of ESP8285 is same of ESP8266. that is, UART0 can be only one of the following configuration.
- (**Option A**) TX: GPIO1, RX: GPIO3, CTS: GPIO13, RTS: GPIO15 (esp8266 sdk default way)
- (**Option B**) TX: GPIO15, RX: GPIO13, CTS: GPIO3, RTS: GPIO1 (esp-at sdk default way)

use [uart_enable_swap()](https://github.com/espressif/esp-at/blob/master/main/interface/uart/at_uart_task.c#L404) to switch between **Option A** and **Option B**.

As u can see, `ESP8266_1MB` AT use  (**Option B**) to config UART0 in application. The purpose of doing this, is to prevent both the AT log and rom log from being output from **Option A**. (1st bootloader uses **Option A** cfg in mandatory)

As u mentioned in your case, wanna use  **Option A** to cfg UART0. this is the esp8266 sdk default way to config UART0.  
AT code will assert tx_pin and rx_pin [here](https://github.com/espressif/esp-at/blob/master/main/interface/uart/at_uart_task.c#L408). and AT uses unidirectional flow control (RTS) [here](https://github.com/espressif/esp-at/blob/master/main/interface/uart/at_uart_task.c#L279). ESP-AT uses unidirectional flow control instead of bidirectional flow control by default, based on compatibility.  
**If u wanna use UART0 bidirectional flow control**, plz use AT command [AT+UART_CUR](https://docs.espressif.com/projects/esp-at/en/latest/AT_Command_Set/Basic_AT_Commands.html#cmd-uartc) or [AT+UART_DEF](https://docs.espressif.com/projects/esp-at/en/latest/AT_Command_Set/Basic_AT_Commands.html#cmd-uartd).

btw, the following code had been wrapped to esp8266 sdk. u can found them in file: [esp-at/esp-idf/components/esp8266/driver/uart.c](https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/components/esp8266/driver/uart.c)
```
PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTDO_U, FUNC_U0RTS);
PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTCK_U, FUNC_UART0_CTS);
```
