### ISSUE TITLE
Change transmit interval on ESP8266/v2.2.0.0

### ISSUE THREAD

**Issue by Lafikateh** [espressif/esp-at#700]
The "AT+CIPSEND" command has a fixed interval of 20 miliseconds if the packet is smaller than 1460 bytes.
Is there any way to change or disable it?
Either as an AT command or a firmware build option?

**Comment by ustccw** [comment]
similar issue to https://github.com/espressif/esp-at/issues/671. Sorry that ESP8266-AT doesn't have a plan to support such feature. here are two possible workaround.
1. please consider use ESP32-C2/ESP32/ESP32-C3 chip instead of ESP8266.
2. i can provide a [libesp8266_at_core.a](https://github.com/espressif/esp-at/blob/release/v2.2.0.0_esp8266/components/at/lib/libesp8266_at_core.a) for you. (but this feature would not sync to release/v2.2.0.0 branch).
